name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build_aar:
    name: Build
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_FILE_PATH: /home/runner/secretKey.gpg
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
            #After decoding the secret key, place the file in ~ /. Gradle/ secring.gpg
      - uses: actions/checkout@v1
      - uses: ./.github/actions/decode_signing_key_action
      - name: Assemble
        run: ./gradlew --stacktrace assemble
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_FILE: ${{ env.SIGNING_KEY_FILE_PATH }}