name: Publish to Maven
on: [pull_request, workflow_dispatch]
jobs:
  publish:
    name: Publish to Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      #After decoding the secret key, place the file in ~ /. Gradle/ secring.gpg
      - name: Decode secret key
        run: |
            echo "${{secrets.SIGNING_KEY_FILE}}" > ~/secretKey.gpg.b64
            base64 -d ~/secretKey.gpg.b64 > /home/runner/work/Android-SDK/Android-SDK/secretKey.gpg
      - name: Publish Card Module
        run: ./gradlew --stacktrace clean :Card:publishReleasePublicationToMavenRepository
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_FILE: /home/runner/work/Android-SDK/Android-SDK/secretKey.gpg

      - name: Publish Core Module
        run: ./gradlew --stacktrace clean :Core:publishReleasePublicationToMavenRepository
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_FILE: /home/runner/work/Android-SDK/Android-SDK/secretKey.gpg
